name: Create Github Release

on:
  push:
    tags:
      - '**'

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - name: log tag
        uses: chrimaeon/github-create-release-action@0.1.0-alpha01
        with:
          tag: ${{ github.ref }}
          description: "this is a sample description"