name: Create Github Release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - name: log tag
        uses: chrimaeon/github-create-release-action@0.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          description: "this is a sample description"